In [1]:
import numpy as np

# Câu 1: Tạo array art có kích thước 3x3 với các giá trị True
art = np.full((3, 3), True)
print("Array art (3x3 với giá trị True):")
print(art)

Array art (3x3 với giá trị True):
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [7]:
 #Câu 2: Tạo array 2 chiều từ arr_ID và đổi cột 1 và cột 3
arr_ID = np.array([0, 12345678])  # Định dạng đúng cho arr_ID
arr_2D = np.array([[arr_ID[0], arr_ID[1], arr_ID[1]],   # Cột 1, cột 2, cột 3
                   [arr_ID[0], arr_ID[1], arr_ID[1]],   # Lặp lại để tạo mảng 3x3
                   [arr_ID[0], arr_ID[1], arr_ID[1]]])  # Lặp lại để tạo mảng 3x3

# Đổi cột 1 và cột 3 trong arr_2D
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print("\nArray arr_2D sau khi đổi cột 1 và cột 3:")
print(arr_2D)



Array arr_2D sau khi đổi cột 1 và cột 3:
[[12345678 12345678        0]
 [12345678 12345678        0]
 [12345678 12345678        0]]


In [8]:
# Câu 3: Đổi dòng 1 và dòng 2
arr_2D[[0, 1], :] = arr_2D[[1, 0], :]
print("\nArray arr_2D sau khi đổi dòng 1 và dòng 2:")
print(arr_2D)



Array arr_2D sau khi đổi dòng 1 và dòng 2:
[[12345678 12345678        0]
 [12345678 12345678        0]
 [12345678 12345678        0]]


In [9]:
# Câu 4: Đảo ngược các dòng của arr_2D
arr_2D = arr_2D[::-1]
print("\nArray arr_2D sau khi đảo ngược các dòng:")
print(arr_2D)


Array arr_2D sau khi đảo ngược các dòng:
[[12345678 12345678        0]
 [12345678 12345678        0]
 [12345678 12345678        0]]


In [10]:
# Câu 5: Đảo ngược các cột của arr_2D
arr_2D = arr_2D[:, ::-1]
print("\nArray arr_2D sau khi đảo ngược các cột:")
print(arr_2D)


Array arr_2D sau khi đảo ngược các cột:
[[       0 12345678 12345678]
 [       0 12345678 12345678]
 [       0 12345678 12345678]]


In [13]:
# Câu 6: Tạo mảng 2D có giá trị NaN
arr_2D_null = np.array([[1, 2, 3], [np.nan, 5, 6], [7, np.nan, 9], [4, 5, 6]])

# Kiểm tra trong array có giá trị rỗng (NaN) không
has_nan = np.isnan(arr_2D_null).any()
print("\nKiểm tra giá trị rỗng (NaN) trong arr_2D_null:", has_nan)


Kiểm tra giá trị rỗng (NaN) trong arr_2D_null: True


In [14]:
# Câu 7: Thay thế giá trị NaN bằng 0
arr_2D_null[np.isnan(arr_2D_null)] = 0
print("\nArray arr_2D_null sau khi thay thế giá trị NaN bằng 0:")
print(arr_2D_null)


Array arr_2D_null sau khi thay thế giá trị NaN bằng 0:
[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
